config/routes.rb
Ft::Application.routes.draw do
  namespace :admin do resources :roles end
  namespace :admin do resources :users end	

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/role.rb
class Admin::Role < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  attr_accessible :name
  validates :name, :presence => true, :uniqueness => true
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role_ids
  
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < ApplicationController
  load_and_authorize_resource
  
  def index
  
    @admin_roles = Role.all  
    respond_to do |format|
      format.html
      format.json { render json: @admin_roles }
    end
  end

  
  def show
    @admin_role = Role.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @admin_role }
    end
  end

  def new
    @admin_role = Role.new
    respond_to do |format|
      format.html
      format.json { render json: @admin_role }
    end
  end

  
  def edit
    @admin_role = Role.find(params[:id])
  end

  
  def create
    @admin_role = Role.new(params[:role])    
    respond_to do |format|
      if @admin_role.save
        format.html { redirect_to users_path, notice: 'Role was successfully created.' }
        format.json { render json: @admin_role, status: :created, location: @admin_role }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_role.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    @admin_role = Role.find(params[:id])
    respond_to do |format|
      if @admin_role.update_attributes(params[:role])
        format.html { redirect_to users_path, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_role.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @admin_role = Role.find(params[:id])
    @admin_role.destroy    
    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource
  
  def edit
    @admin_user = User.find(params[:id])
  end

  def update
    @admin_user = User.find(params[:id])
    respond_to do |format|
      if @admin_user.update_attributes(params[:user])
        format.html { redirect_to users_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_role.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/admin/roles_helper.rb
module Admin::RolesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/roles/_form.html.erb
<%= form_for @admin_role, :url => {:controller => "admin/roles", :action => "create" } do |f| %>
  <% if @admin_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_role.errors.count, "error") %> prohibited this admin_role from being saved:</h2>

      <ul>
      <% @admin_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label "Name" %>
    <%= f.text_field :name %><br/>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/roles/_form_edit.html.erb
<%= form_for @admin_role, :url => {:controller => "admin/roles", :action => "update" } do |f| %>
  <% if @admin_role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_role.errors.count, "error") %> prohibited this admin_role from being saved:</h2>

      <ul>
      <% @admin_role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label "Name" %>
    <%= f.text_field :name %><br/>
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Editing admin_role</h1>

<%= render 'form_edit' %>
<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/index.html.erb
<h1>Listing admin_roles</h1>

<table class="table">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_roles.each do |admin_role| %>    
  <tr>
    <td>      
      <%= admin_role.name %>
    </td>
    <td>      
      <%= link_to "Edit", {:action => "edit", :id => admin_role.id, :method => "put"} %>
    </td>
    <td>      
      <%= link_to "Delete", {:action => "destroy", :id => admin_role.id}, :method => "delete" %>
    </td>
  </tr>  
<% end %>

</table>

<br />

<%= link_to 'New Role', new_admin_role_path %>

app/views/admin/roles/new.html.erb
<h1>New admin_role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_role_path(@admin_role) %> |
<%= link_to 'Back', admin_roles_path %>

app/views/admin/users/edit.html.erb
<h1>Editing admin_user</h1>
<%= form_for @admin_user, :url => {:controller => "admin/users", :action => "update" } do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label "Name" %>
    <%= f.text_field :name %><br/>
    <h4>Roles associated with user</h4>    
    <% Role.all.each do |role| %>
      <%= role.name %>
      <%= check_box_tag 'user[role_ids][]', role.id, @admin_user.roles.include?(role) ? true:false %>
      <br/>
    <% end %>    
    <%= f.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<h3>Home</h3>
<table>  
  <% @users.each do |user| %>
    <tr>
      <td>	
        <p>User: <%=link_to user.name, user %></p>
      </td>      
    </tr>  
  <% end %>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "FT", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= content_for?(:title) ? yield(:title) : "Ft" %></title>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/users/_roles.html.erb
<p>
  <h3>Roles</h3>
  <% Role.all.each do |role| %>
    <p><%= role.name %></p>
  <% end %>
</p>

app/views/users/index.html.erb
<h3>Users</h3>
<table>  
  <% @users.each do |user| %>
    <tr>
      <td>	
        <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
      </td>
      <td>
        <%= link_to "Edit", {:controller => "admin/users", :action => "edit", :id => user.id} %>  
      </td>	
    </tr>  
  <% end %>
</table>


<%= render :partial => "roles" %>
<h2><%= link_to "Manage Roles", {:controller => "admin/roles", :action => "index"} %></h2>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>